- name: Create Tandoor postgres data directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "70"
    group: "70"
    mode: "0700"
  loop:
    - "{{ database_dir }}/tandoor"
    - "{{ database_dir }}/tandoor/pgdata"
  tags:
    - kitchen

- name: Create Tandoor media and compose directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ media_path }}/recipes"
    - "{{ media_path }}/recipes/mediafiles"
    - "{{ compose_root }}/kitchen"
  tags:
    - kitchen

- name: create .env file for kitchen stack
  copy:
    dest: "{{ compose_root }}/kitchen/.env"
    owner: root
    group: docker
    mode: "0640"
    content: |
      HOST_IP={{ host_ip }}
      HOST_TANDOOR={{ tunnel_hosts.tandoor }}
      HOST_AUTHENTIK={{ tunnel_hosts.authentik }}
      OIDC_TANDOOR_SECRET={{ oidc_tandoor_secret }}
      RECIPES_DB_NAME=recipes
      RECIPES_DB_USER=djangodb
      RECIPES_DB_PASSWORD={{ tandoor_postgres_password }}
      RECIPES_SECRET_KEY={{ tandoor_secret_key }}
      CONFIG_PATH={{ config_path }}
      DATABASE_DIR={{ database_dir }}
      MEDIA_PATH={{ media_path }}
  tags:
      - kitchen

- name: run kitchen compose file
  community.docker.docker_compose_v2:
    project_src: "{{ compose_root }}/kitchen"
    files: kitchen.yml
  tags:
    - kitchen
