app_dir: "{{ cache_dir }}/hevy-insights"
compose_file: "{{ compose_root }}/fitness/fitness.yml"
repo_url: https://github.com/casudo/Hevy-Insights.git
api_key: klean_kanteen_insulated
frontend_port: 8123
