- name: Configure audiobookrequest
  ansible.builtin.import_tasks: audiobookrequest.yml
  tags:
    - arr
    - arr-audiobookrequest

- name: Configure bazarr
  ansible.builtin.import_tasks: bazarr.yml
  tags:
    - arr
    - arr-bazarr

- name: Configure Bookshelf
  ansible.builtin.import_tasks: bookshelf.yml
  tags:
    - arr
    - arr-bookshelf

- name: deploy arr docker stack
  ansible.builtin.import_tasks: docker.yml
  tags:
    - arr
    - arr-docker

- name: Configure gluetun
  ansible.builtin.import_tasks: gluetun.yml
  tags:
    - arr
    - arr-gluetun

- name: Configure Lidarr
  ansible.builtin.import_tasks: lidarr.yml
  tags:
    - arr
    - arr-lidarr

- name: Configure overseerr
  ansible.builtin.import_tasks: overseerr.yml
  tags:
    - arr
    - arr-overseerr

- name: Configure Prowlarr
  ansible.builtin.import_tasks: prowlarr.yml
  tags:
    - arr
    - arr-prowlarr

- name: Configure qbittorrent
  ansible.builtin.import_tasks: qbittorrent.yml
  tags:
    - arr
    - arr-qbittorrent

- name: Configure Radarr
  ansible.builtin.import_tasks: radarr.yml
  tags:
    - arr
    - arr-radarr

- name: Configure slskd
  ansible.builtin.import_tasks: slskd.yml
  tags:
    - arr
    - arr-slskd

- name: Configure Sonarr
  ansible.builtin.import_tasks: sonarr.yml
  tags:
    - arr
    - arr-sonarr

- name: Configure Whisparr
  ansible.builtin.import_tasks: whisparr.yml
  tags:
    - arr
    - arr-whisparr

- name: Configure cross-seed
  ansible.builtin.import_tasks: cross-seed.yml
  tags:
    - arr
    - arr-cross-seed



