- name: Create config directory for overseerr 
  file:
    path: "{{ config_dir }}/overseerr"
    state: directory
    owner: 1000
    group: 1000
    mode: "0640"

- name: Wait for Overseerr to be up
  uri:
    url: "http://{{ ansible_ssh_host }}:5055/api/v1/status"
    method: GET
    status_code: 200
  register: overseerr_ping
  retries: 30
  delay: 2
  until: overseerr_ping.status == 200

- name: Read Overseerr config
  slurp:
    src: "{{ config_dir }}/overseerr/settings.json"
  register: overseerr_config_raw

- name: Decode Overseerr settings
  set_fact:
    overseerr_config: >-
      {{ overseerr_config_raw.content | b64decode | from_json }}


- name: Extract Overseer API Key
  set_fact:
    overseerr_api_key: "{{ overseerr_config.main.apiKey}}"


- name: Login via Plex Token
  uri:
    url: "http://{{ ansible_ssh_host }}:5055/api/v1/auth/plex"
    method: POST
    body_format: json
    body:
      authToken: "{{ plex_token }}"
    status_code: 200
    return_content: true
  register: overseerr_auth
  ignore_errors: yes
