- name: Create config directory for qbittorrent
  file:
    path: "{{ config_path }}/qbittorrent"
    state: directory
    owner: 1000
    group: 1000
    mode: "0750"

- name: qBittorrent Configuration Block
  block:
    - name: Set qBittorrent variable facts
      set_fact:
        qbittorrent_config_file: "{{ config_path }}/qbittorrent/qBittorrent/qBittorrent.conf"
        qbt_settings: 
          - { section: "BitTorrent", option: "Session\\SavePath", value: "/data/downloads/torrents/" }
          - { section: "BitTorrent", option: "Session\\TempPath", value: "/data/downloads/torrents/incomplete/" }
          - { section: "BitTorrent", option: "Session\\TempPathEnabled", value: "true" }
          - { section: "BitTorrent", option: "Session\\LSDEnabled", value: "false" }
          - { section: "BitTorrent", option: "Session\\PeXEnabled", value: "false" }
          - { section: "BitTorrent", option: "Session\\DHTEnabled", value: "false" }
          - { section: "Preferences", option: "WebUI\\LocalHostAuth", value: "false" }
          - { section: "Preferences", option: "WebUI\\CSRFProtection", value: "false" }
          - { section: "Preferences", option: "WebUI\\AuthSubnetWhitelistEnabled", value: "true" }
          - { section: "Preferences", option: "WebUI\\AuthSubnetWhitelist", value: "172.0.0.0/8" }

    - name: Ensure qBittorrent config dir exists
      file:
        path: "{{ config_path }}/qbittorrent/qBittorrent"
        state: directory
        owner: 1000
        group: 1000
        mode: "0775"

    - name: Check if qBittorrent config requires updates
      community.general.ini_file:
        path: "{{ qbittorrent_config_file }}"
        section: "{{ item.section }}"
        option: "{{ item.option }}"
        value: "{{ item.value }}"
        create: yes
      loop: "{{ qbt_settings }}"
      check_mode: yes
      register: qbit_config_check

    - name: Apply changes if required
      block:
        - name: Check qbittorrent container status
          community.docker.docker_container_info:
            name: qbittorrent
          register: qbittorrent_info

        - name: Stop qbittorrent to prevent config overwrite
          community.docker.docker_container:
            name: qbittorrent
            state: stopped
          when: qbittorrent_info.exists and qbittorrent_info.container.State.Running

        - name: Apply qBittorrent Settings
          community.general.ini_file:
            path: "{{ qbittorrent_config_file }}"
            section: "{{ item.section }}"
            option: "{{ item.option }}"
            value: "{{ item.value }}"
            create: yes
            mode: "0664"
            owner: 1000
            group: 1000
          loop: "{{ qbt_settings }}"

        - name: Start qbittorrent container
          community.docker.docker_container:
            name: qbittorrent
            state: started
          when: qbittorrent_info.exists

      when: qbit_config_check.changed
