- name: Create config directory for radarr
  file:
    path: "{{ config_dir }}/radarr"
    state: directory
    owner: 1000
    group: 1000
    mode: "0640"

- name: wait for Radarr to be up
  uri:
    url: "http://{{ ansible_ssh_host }}:7878/radarr/ping"
    method: GET
    status_code: 200
  register: radarr_ping
  retries: 30
  delay: 2
  until: radarr_ping.status == 200

- name: Get Radarr root folders
  uri:
    url: "http://{{ ansible_ssh_host }}:7878/api/v3/rootfolder"
    method: GET
    headers:
      X-Api-Key: "{{ radarr_api_key }}"
    return_content: true
  register: radarr_root_folders

- name: Build Radarr root folder
  set_fact:
    radarr_root_folder_body:
      path: "/data/media/movies"

- name: Create Radarr root folder if it does not exist with this path
  when: >
    (radarr_root_folders.json
    | selectattr('path', 'contains', '/data/media/movies')
    | list
    | length) == 0
  uri:
    url: "http://{{ ansible_ssh_host }}:7878/api/v3/rootfolder"
    method: POST
    headers:
      X-Api-Key: "{{ radarr_api_key }}"
    body_format: json
    body: "{{ radarr_root_folder_body }}"
    status_code: [200, 201]
    return_content: true
  register: radarr_rootfolder_create


- name: Get existing download clients
  uri:
    url: "http://{{ ansible_ssh_host }}:7878/api/v3/downloadclient"
    method: GET
    headers:
      X-Api-Key: "{{ radarr_api_key }}"
    return_content: true
  register: radarr_downloadclients

- name: Extract Downloadclient IDs
  set_fact:
    radarr_downloadclient_id_list: >-
      {{ radarr_downloadclients.json
        | map(attribute='id')
        | list }}

- name: Build qbittorrent application body
  set_fact:
    radarr_qbittorrent_body:
      name: "qBittorrent"
      enable: true
      protocol: "torrent"
      priority: 1
      removeCompletedDownloads: false
      removeFailedDownloads: true
      fields:
        - name: "host"
          value: "gluetun"
        - name: "port"
          value: 8088
        - name: "useSsl"
          value: false
        - name: "username"
          value: "{{ qbittorrent_username }}"
        - name: "password"
          value: "{{ qbittorrent_password }}"
      implementationName: "qBittorrent"
      implementation: "QBittorrent"
      configContract: "QBittorrentSettings"

- name: Create qbittorrent download client if missing
  when: >
    (radarr_downloadclients.json
      | selectattr('implementation', 'equalto', 'QBittorrent')
      | list
      | length) == 0
  uri:
    url: "http://{{ ansible_ssh_host }}:7878/api/v3/downloadclient"
    method: POST
    headers:
      X-Api-Key: "{{ radarr_api_key }}"
    body_format: json
    body: "{{ radarr_qbittorrent_body }}"
    status_code: [200, 201]
    return_content: true
  register: radarr_qbittorrent_create
  ignore_errors: yes


