- name: Create config directory for slskd
  file:
    path: "{{ config_path }}/slskd"
    state: directory
    owner: 1000
    group: 1000
    mode: "0750"

- name: Create temp download directory for slskd 
  file:
    path: "{{ item }}"
    state: directory
    owner: 1000
    group: 1000
    mode: "0750"
  loop:
    - "{{ torrent_path }}/downloads"
    - "{{ torrent_path }}/downloads/complete"
    - "{{ torrent_path }}/downloads/incomplete"
