- name: make .env file for productivity stack
  copy:
    dest: "{{ compose_root }}/productivity/.env"
    owner: root
    group: docker
    mode: "0640"
    content: |
      HOST_IP={{ host_ip }}
      VIKUNJA_PASSWORD={{ vikunja_password }}
      VIKUNJA_JWT_SECRET={{ vikunja_jwt_secret }}
      COMPOSE_ROOT={{ compose_root }}
      VIKUNJA_POSTGRES_PASSWORD={{ vikunja_postgres_password }}
      DATABASE_DIR={{ database_dir }}
  tags:
    - productivity

- name: run productivity compose file
  community.docker.docker_compose_v2:
    project_src: "{{ compose_root }}/productivity"
    files: productivity.yml
  tags:
    - productivity
