- name: add compose root to git safe directories
  ansible.builtin.command:
    cmd: git config --global --add safe.directory '{{ item }}'
  become: true
  changed_when: false
  loop:
    - "{{ compose_root }}"
    - "{{ config_path }}"
  tags:
    - docker

- name: clone repository containing compose files
  ansible.builtin.git:
    repo: 'https://github.com/MoritzPalm/home_server_compose.git'
    dest: '{{ compose_root }}'
    accept_newhostkey: true
    single_branch: yes
    version: main
    force: true
  tags:
    - docker

- name: create admin password file for portainer
  copy:
    dest: "{{ compose_root }}/portainer/admin_password.txt"
    owner: root
    group: docker
    mode: "0640"
    content: "{{ portainer_admin_password }}"

- name: create env file for portainer
  copy:
    dest: "{{ compose_root }}/portainer/.env"
    owner: root
    group: docker
    mode: "0640"
    content: |
      ADMIN_PASSWORD_FILE={{ compose_root }}/portainer/admin_password.txt
      PORTAINER_LICENSE_KEY={{ portainer_license_key }}

- name: Create shared Docker network for media services
  community.docker.docker_network:
    name: media_network
    state: present
  tags:
    - docker
    - networking

- name: run portainer docker compose file
  community.docker.docker_compose_v2:
    project_src: "{{ compose_root }}/portainer"
    files: "portainer.yml"



