timezone: Europe/Berlin
admin_user: moritzpalm

compose_root: /srv/compose
config_path: /srv/data/configs
database_dir: /srv/data/db
cache_dir: /srv/data/cache
media_path: /mnt/storage/media
torrent_path: /mnt/storage/downloads/torrents
downloads_path: /mnt/storage/downloads
soulseek_path: /mnt/storage/downloads/soulseek
storage_path: /mnt/storage
backup_path: /mnt/backups
log_dir: /srv/logs

ssd_dirs:
  - "/srv/compose"
  - "/srv/data/configs"
  - "/srv/data/db"
  - "/srv/data/cache"
  - "/srv/logs"

tailscale_operator: "moritzpalm"

plex_url: "100.78.131.48:32401"
