timezone: Europe/Berlin
admin_user: moritzpalm

compose_root: /srv/compose
config_path: /srv/data/configs
database_dir: /srv/data/db
cache_dir: /srv/data/cache
media_path: /mnt/storage/media
media_library_dirs:
  - "{{ media_path }}/movies"
  - "{{ media_path }}/tv"
  - "{{ media_path }}/music"
  - "{{ media_path }}/books"
  - "{{ media_path }}/xxx"
torrent_path: /mnt/storage/downloads/torrents
downloads_path: /mnt/storage/downloads
soulseek_path: /mnt/storage/downloads/soulseek
storage_path: /mnt/storage
backup_path: /mnt/backups
log_dir: /srv/logs

ssd_dirs:
  - "/srv/compose"
  - "/srv/data/configs"
  - "/srv/data/db"
  - "/srv/data/cache"
  - "/srv/logs"

admin_ssh_public_keys:
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO4Fe+sdTMI8vP5Ka2gEuzpWfgCf1oTCQ8z1KSLgxR04 moritz.palm@web.de"

tailscale_operator: "moritzpalm"

plex_url: "100.78.131.48:32401"
