- name: Create stash config directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - "{{ config_path }}/stash"
    - "{{ config_path }}/stash/generated"
    - "{{ config_path }}/stash/cache"
