- hosts: regensburg
  become: true
  force_handlers: true
  roles:
    - tailscale
    - base
    - storage
    - geerlingguy.docker
    - docker
    - homepage
    - arr
    - media
    - monitoring
    - fitness
    - kitchen
    - productivity
